
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-user-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-user-saver
  template:
    metadata:
      labels:
        app: github-user-saver
    spec:
      containers:
      - name: github-user-saver
        image: github-user-saver:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 9090