
apiVersion: v1
kind: Service
metadata:
  name: github-user-saver-service
spec:
  type: NodePort
  selector:
    app: github-user-saver
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30080